import range.SimpleRange

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {

    static void main(String[] args) {
        println('App.main ....')

        SimpleRange sr = new SimpleRange()
        sr.runMethods()
    }
}
