import ranges.SimpleRange
import getterSetter.Point

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {


    static void main(String[] args) {
        println('### App.main ....')

        
        SimpleRange sr = new SimpleRange()
        sr.runMethods()

        Point point = new Point()
        point.x = 15
        point.y = 16
        point.sum()
        

   }
}
